package com.levy.mango.admin.mapper;

import com.levy.mango.admin.model.SysRoleDept;

public interface SysRoleDeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_dept
     *
     * @mbggenerated Thu Jan 16 20:41:11 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_dept
     *
     * @mbggenerated Thu Jan 16 20:41:11 CST 2020
     */
    int insert(SysRoleDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_dept
     *
     * @mbggenerated Thu Jan 16 20:41:11 CST 2020
     */
    int insertSelective(SysRoleDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_dept
     *
     * @mbggenerated Thu Jan 16 20:41:11 CST 2020
     */
    SysRoleDept selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_dept
     *
     * @mbggenerated Thu Jan 16 20:41:11 CST 2020
     */
    int updateByPrimaryKeySelective(SysRoleDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_dept
     *
     * @mbggenerated Thu Jan 16 20:41:11 CST 2020
     */
    int updateByPrimaryKey(SysRoleDept record);
}