# tomcat
server:
  port: 8002
spring:
  application:
    name: mango-backup
  boot:
    admin:
      client:
        url: "http://localhost:8000"
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: ${spring.application.name}
        enabled: true #是否启用服务发现
        deregister: true # 服务停止时取消注册
        register: true # 开启服务注册
# backup datasource
mango:
  backup:
    datasource:
      host: localhost
      username: root
      password: 123123
      database: mango
# 开放健康检查接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always